name: first-interaction
on: [pull_request, issues]

jobs:
  first-interaction:
    name: "WelcomeBot 🦖"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: '# 🎉 Thank you for opening an issue! 🎉 \n One of the maintainers of the project will respond as soon as possible. Seeing that you are new here, please familiarize yourself with our [code of conduct](https://github.com/mdn/mdn-minimalist/blob/main/CODE_OF_CONDUCT.md)'
          pr-message: '# 🎉 Welcome to Minimalist! 🎉 \n One of the maintainers of the project will respond here as soon as possible. Seeing that you are new here, please familiarize yourself with our [code of conduct](https://github.com/mdn/mdn-minimalist/blob/main/CODE_OF_CONDUCT.md)'
